(function(root){
  const PV=root.PV2000=root.PV2000||{},X=PV.xml,S=PV.stats,q=1.60218e-19,k=1.38e-23,T=300;
  const finite=a=>(a||[]).filter(Number.isFinite),mean=S.mean;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(v,n=3)=>!Number.isFinite(v)?'—':Math.abs(v)>1e4||Math.abs(v)<1e-2?v.toExponential(n):v.toFixed(n);
  const sci=(v,n=3)=>!Number.isFinite(v)?'—':v.toExponential(n-1).replace('e+','e');
  const help=t=>`<span class="help" title="${esc(t)}">i</span>`;
  function scalarMean(e){return e?mean([...e.children].map(x=>Number(x.textContent))):NaN}
  function vectorMeans(e){return e?[...e.children].map(scalarMean):[]}
  function settings(m,name){const n=X.direct(m,name),s=X.direct(n,'Settings'),tr=X.direct(s,'TargetRange');return{charge:X.num(s,'CoronaCharge'),attempts:X.num(s,'MaxNumberOfAttemps'),extra:X.num(s,'ExtraScans'),delay:X.num(s,'ChargeDelay'),targetMin:X.text(tr,'Min',''),targetMax:X.text(tr,'Max','')}}

  function parse(parsed){
    const m=parsed.measurement,c=X.common(parsed),md=X.direct(m,'MeasurementData'),off=X.num(md,'VcpdOffsett',0),factor=X.num(md,'VsbCorrectionFactor',1.2),proc=X.direct(m,'Process'),qstep=X.num(X.direct(proc,'Settings'),'CoronaCharge'),pre=X.direct(m,'PreProcess'),prestep=X.num(X.direct(pre,'Settings'),'CoronaCharge'),data=X.direct(X.direct(X.direct(md,'IterationData'),'Iteration'),'Data'),items=data?X.children(data).filter(e=>X.lname(e)==='DataItem'):[],pattern=X.direct(m,'Pattern'),coeff=X.direct(pattern,'Coefficients'),coords=coeff?X.children(coeff).map(p=>({x:X.num(p,'X',0),y:X.num(p,'Y',0)})):[],sites=[];
    items.forEach((it,si)=>{
      const pd=X.direct(it,'ProcessData'),pred=X.direct(it,'PreProcessData'),d=vectorMeans(X.direct(pd,'VcpdDark')),l=vectorMeans(X.direct(pd,'VcpdLight')),rows=[];
      for(let j=1;j<Math.min(d.length,l.length);j++){const vd=d[j]-off,vl=l[j]-off;rows.push({Qc:(j-1)*qstep,VDark:vd,VLight:vl,Vsb:Math.abs(factor*(vl-vd)),rawDiff:vl-vd})}
      const id=scalarMean(X.direct(it,'InitialVcpdDark'))-off,il=scalarMean(X.direct(it,'InitialVcpdLight'))-off,iv=Math.abs(factor*(id-il));
      sites.push({rows,coord:coords[si]||{x:si,y:0},VDark:id,VLight:id-iv,Vsb:iv,InitialQc:Number.isFinite(prestep)?X.children(X.direct(pred,'VcpdDark')).length*prestep:NaN});
    });
    const qit=X.direct(m,'QitBarrierRange');
    return{...c,doping:X.num(m,'Doping',1.5e15),dopingType:X.text(m,'DopingType','NType').toLowerCase().startsWith('n')?'n':'p',factor,offset:off,sites,
      useCocosII:X.text(m,'UseCocosII','false').toLowerCase()==='true',cocosIIEOT:X.num(m,'CocosIIEOT',NaN),qitMin:X.num(qit,'Min',NaN),qitMax:X.num(qit,'Max',NaN),numberOfDataPoints:X.num(m,'NumberOfDataPoints',NaN),measurementInterval:X.num(m,'MeasurementInterval',NaN),patternType:X.attrType(pattern),patternName:X.text(pattern,'Name',''),pre:settings(m,'PreProcess'),process:settings(m,'Process'),post:settings(m,'PostProcess')};
  }

  function qsc(vsb,doping,type){
    const ni=1e10*1e6,eps0=8.85e-12,eps=11.68,Nd=doping*1e6,p0=type==='p'?Nd:ni*ni/Nd,n0=type==='n'?Nd:ni*ni/Nd,beta=q/(k*T),sg=vsb<=0?1:-1,maj=type==='p'?p0:n0,minrat=type==='p'?n0/p0:p0/n0,term=(Math.exp(-beta*vsb)+beta*vsb-1)+minrat*(Math.exp(beta*vsb)-beta*vsb-1);
    return sg*Math.sqrt(2*k*T*eps0*eps*maj)*Math.sqrt(Math.max(0,term))*1e-4/q;
  }
  function linSlope(x,y){const n=Math.min(x.length,y.length);let sx=0,sy=0,sxx=0,sxy=0,kc=0;for(let i=0;i<n;i++)if(Number.isFinite(x[i])&&Number.isFinite(y[i])){sx+=x[i];sy+=y[i];sxx+=x[i]*x[i];sxy+=x[i]*y[i];kc++}return kc>1?(kc*sxy-sx*sy)/(kc*sxx-sx*sx):NaN}
  function inv(qc,v,t){for(let i=0;i<v.length-1;i++)if((v[i]-t)*(v[i+1]-t)<=0&&v[i+1]!==v[i])return qc[i]+(t-v[i])/(v[i+1]-v[i])*(qc[i+1]-qc[i]);return NaN}
  function interp(qc,v,x){for(let i=0;i<qc.length-1;i++)if(x>=Math.min(qc[i],qc[i+1])&&x<=Math.max(qc[i],qc[i+1])&&qc[i+1]!==qc[i])return v[i]+(x-qc[i])/(qc[i+1]-qc[i])*(v[i+1]-v[i]);return NaN}
  function flat(site,d,accumN=5){
    const r=site.rows;if(r.length<8)return{};const qc=r.map(x=>x.Qc),v=r.map(x=>x.VDark),n=Math.max(3,Math.min(20,accumN)),start=d.dopingType==='n'?Math.max(0,r.length-n):0,end=d.dopingType==='n'?r.length:Math.min(n,r.length),mox=linSlope(qc.slice(start,end),v.slice(start,end)),eps0=8.8541878128e-14,eps=11.68,Cs=Math.sqrt(eps*eps0*q*q*d.doping/(k*T)),mfb=mox+q/Cs,sl=[];
    for(let i=0;i<r.length-1;i++)sl.push((v[i+1]-v[i])/(qc[i+1]-qc[i]));let peak=sl.indexOf(Math.max(...sl)),ix=-1;if(d.dopingType==='n'){for(let i=peak;i<sl.length-1;i++)if(sl[i]>=mfb&&sl[i+1]<=mfb){ix=i;break}}else{for(let i=0;i<peak;i++)if(sl[i]<=mfb&&sl[i+1]>=mfb)ix=i}
    const qi=inv(qc,v,site.VDark);if(ix<0||!Number.isFinite(qi)||!Number.isFinite(mox))return{};const qfb=qc[ix]+(mfb-sl[ix])/(sl[ix+1]-sl[ix])*(qc[ix+1]-qc[ix]),Cox=q/mox,eot=3.9*eps0/Cox*1e7;
    return{qinit:qi,qfb,Qtot:qi-qfb,Cox,eot,mox,mfb,slopes:sl,flatIndex:ix,vfbDark:interp(qc,v,qfb)};
  }
  function cocosII(site,d,f){
    if(!d.useCocosII||!Number.isFinite(f.qfb))return{enabled:false};const r=site.rows,qc=r.map(x=>x.Qc),vd=r.map(x=>x.VDark),anchor=Number.isFinite(f.vfbDark)?f.vfbDark:interp(qc,vd,f.qfb),eps0=8.8541878128e-14;
    let slope=NaN,source='dark accumulation';if(Number.isFinite(d.cocosIIEOT)&&d.cocosIIEOT>0){slope=q*(d.cocosIIEOT*1e-7)/(3.9*eps0);source='XML CocosIIEOT'}else slope=f.mox;
    if(!Number.isFinite(slope)||!Number.isFinite(anchor))return{enabled:true,valid:false,source};const light=qc.map(x=>anchor+slope*(x-f.qfb)),vsb=vd.map((v,i)=>Math.abs(v-light[i]));return{enabled:true,valid:true,light,vsb,slope,source,eot:Number.isFinite(slope)?slope*3.9*eps0/q*1e7:NaN};
  }

  function pchipSlopes(x,y){const n=x.length,h=[],delta=[];for(let i=0;i<n-1;i++){h[i]=x[i+1]-x[i];delta[i]=(y[i+1]-y[i])/h[i]}if(n===2)return[delta[0],delta[0]];const d=new Array(n).fill(0);const edge=(h0,h1,d0,d1)=>{let z=((2*h0+h1)*d0-h0*d1)/(h0+h1);if(Math.sign(z)!==Math.sign(d0))z=0;else if(Math.sign(d0)!==Math.sign(d1)&&Math.abs(z)>3*Math.abs(d0))z=3*d0;return z};d[0]=edge(h[0],h[1],delta[0],delta[1]);d[n-1]=edge(h[n-2],h[n-3],delta[n-2],delta[n-3]);for(let i=1;i<n-1;i++){if(delta[i-1]===0||delta[i]===0||Math.sign(delta[i-1])!==Math.sign(delta[i]))d[i]=0;else{const w1=2*h[i]+h[i-1],w2=h[i]+2*h[i-1];d[i]=(w1+w2)/(w1/delta[i-1]+w2/delta[i])}}return d}
  function pchipEval(x,y,xq){if(x.length<2||xq<x[0]||xq>x[x.length-1])return NaN;const d=pchipSlopes(x,y);let i=x.length-2;for(let k=0;k<x.length-1;k++)if(xq>=x[k]&&xq<=x[k+1]){i=k;break}const h=x[i+1]-x[i],t=(xq-x[i])/h,h00=2*t**3-3*t**2+1,h10=t**3-2*t**2+t,h01=-2*t**3+3*t**2,h11=t**3-t**2;return h00*y[i]+h10*h*d[i]+h01*y[i+1]+h11*h*d[i+1]}
  function filteredXY(x,y,reject=2e13){const z=x.map((v,i)=>[v,y[i]]).filter(p=>p.every(Number.isFinite)).sort((a,b)=>a[0]-b[0]),ux=[],uy=[];for(let i=0;i<z.length;){let j=i+1,sum=z[i][1],n=1;while(j<z.length&&Math.abs(z[j][0]-z[i][0])<1e-12){sum+=z[j][1];n++;j++}const xx=z[i][0],yy=sum/n;if((xx<.1||xx>.5)||yy<reject){ux.push(xx);uy.push(yy)}i=j}return{ux,uy}}
  function makeCurve(x,y,d,reject){const {ux,uy}=filteredXY(x,y,reject),target=Math.abs(k*T/q*Math.log(d.doping/9.65e9));if(ux.length<2)return{mid:NaN,curve:[]};const mid=pchipEval(ux,uy,target),curve=[];for(let xx=ux[0];xx<=ux[ux.length-1]+1e-12;xx+=.006)curve.push({x:xx,y:pchipEval(ux,uy,xx)});return{mid,curve}}
  function variation(site,d,reject=2e13,vsbOverride=null){
    const r=site.rows,vs=vsbOverride&&vsbOverride.length===r.length?vsbOverride:r.map(x=>x.Vsb),qc=r.map(x=>x.Qc),qs=vs.map(v=>qsc(v,d.doping,d.dopingType)),raw=[];for(let i=0;i<r.length-1;i++){const dv=vs[i+1]-vs[i],dq=Math.abs(qc[i+1]-qc[i])-Math.abs(qs[i+1]-qs[i]);raw.push(Math.abs(dv)>0?Math.abs(dq)/Math.abs(dv):NaN)}
    const good=finite(raw),x=vs.slice(0,-1),fit=makeCurve(x,raw,d,reject);let p=0;while(p<vs.length&&vs[p]<.010)p++;if(p>=vs.length)p=vs.length-1;const qsurface=qc[p],qeff=qc.map(x=>x-qsurface),qit=qs.map((x,i)=>-x-qeff[i]),direct=[];for(let i=0;i<r.length-1;i++){const dv=vs[i+1]-vs[i],dq=qit[i+1]-qit[i];direct.push(Math.abs(dv)>0?Math.abs(dq/dv):NaN)}const dfit=makeCurve(x,direct,d,reject);return{vsb:vs,raw,min:good.length?Math.min(...good):NaN,mid:fit.mid,curve:fit.curve,directRaw:direct,directMid:dfit.mid,directCurve:dfit.curve,midgapV:Math.abs(k*T/q*Math.log(d.doping/9.65e9))};
  }
  function analyze(d,opts={}){
    const sites=d.sites.map(s=>{const f=flat(s,d,opts.accumN||5),c2=cocosII(s,d,f),usedVsb=c2.valid?c2.vsb:null,v=variation(s,d,opts.ditReject||2e13,usedVsb),mx=finite(v.vsb.map(Math.abs));return{...s,...f,c2,analysisVsb:v.vsb,Dit:v.min,MidgapDit:v.mid,ditRaw:v.raw,ditCurve:v.curve,directRaw:v.directRaw,directCurve:v.directCurve,directMid:v.directMid,midgapV:v.midgapV,Qsc:Math.abs(qsc(s.Vsb,d.doping,d.dopingType)),MaxVsb:mx.length?Math.max(...mx):NaN,valid:mx.length&&Math.max(...mx)>.1}});
    const keys=['Qtot','Dit','MidgapDit','eot','Cox','Qsc','InitialQc','MaxVsb'],stats={};keys.forEach(k=>stats[k]=S.summary(sites.filter(x=>x.valid).map(x=>x[k])));return{sites,stats,options:{accumN:opts.accumN||5,ditReject:opts.ditReject||2e13},mode:d.useCocosII?'COCOS-II':'standard'};
  }

  function svgAxes(W,H,m,xmin,xmax,ymin,ymax,{xFmt=x=>x.toExponential(1),yFmt=y=>y.toFixed(2),logY=false}={}){const X=x=>m.l+(x-xmin)/(xmax-xmin||1)*(W-m.l-m.r),Y=y=>{const yy=logY?Math.log10(y):y,a=logY?Math.log10(ymin):ymin,b=logY?Math.log10(ymax):ymax;return H-m.b-(yy-a)/(b-a||1)*(H-m.t-m.b)};let out=`<rect width="${W}" height="${H}" fill="var(--chart-bg)"/>`;for(let i=0;i<=4;i++){const yy=logY?10**(Math.log10(ymin)+(Math.log10(ymax)-Math.log10(ymin))*i/4):ymin+(ymax-ymin)*i/4,py=Y(yy);out+=`<line x1="${m.l}" x2="${W-m.r}" y1="${py}" y2="${py}" stroke="var(--grid)"/><text x="${m.l-6}" y="${py+3}" text-anchor="end" fill="var(--muted)" font-size="9">${yFmt(yy)}</text>`}for(let i=0;i<=4;i++){const xx=xmin+(xmax-xmin)*i/4,px=X(xx);out+=`<line x1="${px}" x2="${px}" y1="${m.t}" y2="${H-m.b}" stroke="var(--grid2)"/><text x="${px}" y="${H-12}" text-anchor="middle" fill="var(--muted)" font-size="9">${xFmt(xx)}</text>`}return{X,Y,out}}
  function pathXY(x,y,X,Y,color,w=2,dash=''){const pts=x.map((v,i)=>Number.isFinite(v)&&Number.isFinite(y[i])?`${X(v)},${Y(y[i])}`:null).filter(Boolean).join(' ');return `<polyline points="${pts}" fill="none" stroke="${color}" stroke-width="${w}" ${dash?`stroke-dasharray="${dash}"`:''}/>`}
  function metric(s,key){if(key==='EOT')return s.eot;return s[key]}
  function mapSpec(k){return{Qtot:['Qtot','cm⁻²',true],Dit:['Minimum Dit','cm⁻² eV⁻¹',true],MidgapDit:['Midgap Dit','cm⁻² eV⁻¹',true],EOT:['EOT (SiO₂ eq.)','nm',false],Cox:['Cox','F/cm²',true],Qsc:['Qsc','cm⁻²',true],InitialQc:['Initial Qc','cm⁻²',false],MaxVsb:['Max |Vsb|','V',false]}[k]}
  function mapValue(v,k){if(!Number.isFinite(v))return'—';if(k==='EOT')return v.toFixed(2);if(k==='MaxVsb')return v.toFixed(3);const e=Math.floor(Math.log10(Math.abs(v)||1)),m=v/10**e;return`${m.toFixed(2)}e${e}`}
  function mapColor(t){t=Math.max(0,Math.min(1,t));const a=[79,124,255],b=[255,90,95];return`rgb(${Math.round(a[0]+(b[0]-a[0])*t)},${Math.round(a[1]+(b[1]-a[1])*t)},${Math.round(a[2]+(b[2]-a[2])*t)})`}

  function render(host,d,baseAnalysis){
    let analysis=baseAnalysis,site=Math.max(0,analysis.sites.findIndex(x=>x.valid)),showDirect=false,mapKey='Qtot';
    const rebuild=()=>{const accumN=Number(host.querySelector('#ditAccumN')?.value||analysis.options.accumN||5),ditReject=Number(host.querySelector('#ditReject')?.value||analysis.options.ditReject||2e13);analysis=analyze(d,{accumN,ditReject});if(site>=analysis.sites.length)site=0;renderShell()};
    const statText=(key)=>{const st=analysis.stats[key];return st&&Number.isFinite(st.mean)?`${fmt(st.mean)} ± ${fmt(st.stdev)}`:'—'};
    const resultHelp={Qtot:'Total dielectric/interface charge obtained from the horizontal charge separation between the natural initial condition and the flatband point on the dark V–Q characteristic.',Dit:'Minimum interface-state density from the variation method. When XML UseCocosII=true, the corrected COCOS-II Vsb curve is used automatically.',MidgapDit:'PCHIP-interpolated interface-state density at the midgap surface potential.',eot:'Equivalent oxide thickness expressed as the thickness of SiO₂ (κ≈3.9) giving the measured dielectric capacitance. For any other dielectric or multilayer stack it is an electrical-equivalent thickness, not physical thickness.',Cox:'Dielectric capacitance per unit area obtained from the dark accumulation V–Q slope.',Qsc:'Semiconductor space charge evaluated at the natural initial Vsb using the same MOS charge model as the group MATLAB code.',InitialQc:'Barrier-adjustment corona bookkeeping: number of PreProcess charge events multiplied by the PreProcess corona-charge step.',MaxVsb:'Maximum absolute surface-barrier magnitude reached by the analysis Vsb curve; with COCOS-II enabled this uses the reconstructed corrected Vsb.'};
    const metaHelp={recipe:'PV-2000 recipe/job name stored in the result XML.',substrate:'Substrate identifier stored with the result.',lot:'Lot identifier stored with the result; it may be empty.',status:'PV-2000 execution status.',start:'Execution start timestamp from the result XML.',end:'Execution completion timestamp from the result XML.',elapsed:'Total elapsed measurement time.',pattern:'Measurement pattern name/type and number of measured sites.',points:'Number of Kelvin-probe samples averaged for each Vcpd reading.',interval:'Time interval between the Vcpd samples used to form each vector.',offset:'Kelvin-probe Vcpd calibration offset stored in MeasurementData and applied to reconstructed Vcpd values.',factor:'Standard COCOS correction factor applied to the measured dark-light Vcpd difference when COCOS-II is disabled.',qitRange:'Surface-barrier range configured for Qit/Dit extraction.',c2:'Whether the XML requests COCOS-II. When true, this analyzer replaces the experimental light curve with a synthetic straight light curve before Dit extraction.',c2eot:'COCOS-II EOT setting stored in the XML. When COCOS-II is active and this value is finite/positive, it defines the synthetic-light slope; otherwise the dark accumulation slope is used.',preCharge:'Corona charge increment used during barrier adjustment before the main sweep.',preTarget:'Target Vsb range for the barrier-adjustment stage.',preAttempts:'Maximum barrier-adjustment attempts and number of extra scans.',processCharge:'Positive/negative corona charge increment used during the main Process sweep.',processTarget:'Target measurement range for terminating the main Process sweep.',processAttempts:'Maximum Process attempts and number of extra scans.'};
    const md=(label,value,tip)=>`<dt>${esc(label)} ${help(tip)}</dt><dd>${value}</dd>`;
    function renderShell(){
      const s=analysis.sites[site],coord=s.coord||{x:0,y:0},rows=[['Qtot','Qtot'],['Minimum Dit','Dit'],['Midgap Dit','MidgapDit'],['EOT (SiO₂ eq.)','eot'],['Cox','Cox'],['Qsc','Qsc'],['Initial Qc','InitialQc'],['Max |Vsb|','MaxVsb']];
      host.innerHTML=`<div class="module-grid dit-module"><aside class="side">
        <section class="panel"><h3>Measurement ${help('All metadata below is read directly from the imported PV-2000 XML.')}</h3><div class="measurement-title">${esc(d.resultName)}</div><div class="measurement-sub">${d.useCocosII?'<span class="mode-badge good">COCOS-II ON</span>':'<span class="mode-badge">Standard COCOS</span>'} · ${esc(d.dopingType)}-type · ${sci(d.doping,3)} cm⁻³</div><div class="site-controls"><button id="ditPrev">‹</button><select id="ditSite">${analysis.sites.map((x,i)=>`<option value="${i}" ${i===site?'selected':''}>Site ${i+1}${x.valid?'':' ⚠'}</option>`).join('')}</select><button id="ditNext">›</button><span class="coord">x ${fmt(coord.x,1)} · y ${fmt(coord.y,1)}</span></div></section>
        <section class="panel"><h3>Results summary ${help('Valid-site mean uses only sites with a usable surface-barrier sweep. Current-site values correspond to the selected site above.')}</h3><div class="table-wrap"><table><thead><tr><th>Parameter</th><th>Valid-site mean</th><th>Current site</th></tr></thead><tbody>${rows.map(([n,k])=>{const v=metric(s,k),sk=k==='eot'?'eot':k;return`<tr title="${esc(resultHelp[k]||'')}"><td>${n} ${help(resultHelp[k]||'')}</td><td>${statText(sk)}</td><td>${fmt(v)}</td></tr>`}).join('')}</tbody></table></div></section>
        <details class="panel"><summary>Measurement metadata ${help('Detailed recipe, substrate, timing and COCOS settings parsed directly from the imported XML.')}</summary><dl class="meta meta-detail">${md('Recipe',esc(d.name||'—'),metaHelp.recipe)}${md('Substrate ID',esc(d.substrateId||'—'),metaHelp.substrate)}${md('Lot ID',esc(d.lotId||'—'),metaHelp.lot)}${md('Status',esc(d.status||'—'),metaHelp.status)}${md('Start',esc(d.start||'—'),metaHelp.start)}${md('End',esc(d.end||'—'),metaHelp.end)}${md('Elapsed',esc(d.elapsed||'—'),metaHelp.elapsed)}${md('Pattern',`${esc(d.patternName||d.patternType||'—')} · ${analysis.sites.length} sites`,metaHelp.pattern)}${md('Data points / Vcpd',fmt(d.numberOfDataPoints,0),metaHelp.points)}${md('Measurement interval',`${fmt(d.measurementInterval,4)} s`,metaHelp.interval)}${md('Vcpd offset',`${fmt(d.offset,6)} V`,metaHelp.offset)}${md('Vsb factor',fmt(d.factor,3),metaHelp.factor)}${md('Qit barrier range',`${fmt(d.qitMin,3)} to ${fmt(d.qitMax,3)} V`,metaHelp.qitRange)}${md('Use COCOS-II',d.useCocosII?'True':'False',metaHelp.c2)}${md('COCOS-II EOT',`${fmt(d.cocosIIEOT,3)} nm`,metaHelp.c2eot)}</dl></details>
        <details class="panel"><summary>Recipe charge sequence ${help('Corona charge increments, target ranges and loop limits controlling barrier adjustment and the main COCOS sweep.')}</summary><dl class="meta meta-detail">${md('PreProcess ΔQc',`${sci(d.pre.charge,3)} cm⁻²`,metaHelp.preCharge)}${md('PreProcess target',`${esc(d.pre.targetMin)} to ${esc(d.pre.targetMax)}`,metaHelp.preTarget)}${md('Pre attempts / extra',`${fmt(d.pre.attempts,0)} / ${fmt(d.pre.extra,0)}`,metaHelp.preAttempts)}${md('Process ΔQc',`${sci(d.process.charge,3)} cm⁻²`,metaHelp.processCharge)}${md('Process target',`${esc(d.process.targetMin)} to ${esc(d.process.targetMax)}`,metaHelp.processTarget)}${md('Process attempts / extra',`${fmt(d.process.attempts,0)} / ${fmt(d.process.extra,0)}`,metaHelp.processAttempts)}</dl></details>
        <details class="panel"><summary>Flatband extraction</summary><dl class="meta"><dt>q initial ${help('Natural initial dark Vcpd projected onto the Process dark V–Q curve.')}</dt><dd>${sci(s.qinit,4)}</dd><dt>q flatband ${help('Flatband charge obtained from the dark differential-capacitance crossing using the theoretical semiconductor flatband capacitance.')}</dt><dd>${sci(s.qfb,4)}</dd><dt>EOT</dt><dd>${fmt(s.eot,3)} nm</dd><dt>Cox</dt><dd>${sci(s.Cox,4)} F/cm²</dd>${d.useCocosII?`<dt>COCOS-II source ${help('The XML UseCocosII flag is honored. A synthetic light curve is anchored at the same flatband point and uses either XML CocosIIEOT or the dark accumulation slope.')}</dt><dd>${esc(s.c2?.source||'unavailable')}</dd>`:''}</dl></details>
        <details class="panel"><summary>Analysis controls</summary><div class="setting-row"><label>Accumulation fit points ${help('Number of deepest-accumulation dark V–Q points used to determine Cox/EOT and the flatband-capacitance criterion.')}<input id="ditAccumN" type="number" min="3" max="20" value="${analysis.options.accumN}"></label><label>Dit reject threshold ${help('Heuristic upper Dit threshold used only in the 0.1–0.5 V interpolation window before PCHIP midgap evaluation.')}<input id="ditReject" type="number" step="any" value="${analysis.options.ditReject}"></label><button id="ditRecalc">Recalculate</button></div></details>
        <details class="panel"><summary>Audit comparison</summary><label class="checkline"><input id="ditDirect" type="checkbox" ${showDirect?'checked':''}> show legacy direct-charge Dit</label><p class="note">Variation/PCHIP is the primary Dit path. Legacy direct-charge remains only as an audit overlay because its original flatband/orientation assumptions are not reliable for every polarity. ${d.useCocosII?'This XML requests COCOS-II, so the primary variation curve is calculated from the reconstructed corrected Vsb. COCOS-II support is guide-derived and still needs a vendor COCOS-II-on export for exact regression.':''}</p></details>
      </aside><section class="plots">
        <div class="panel chart"><header><b>Vcpd–Qc</b>${help('Dark and measured light Kelvin-probe potentials versus deposited corona charge. For COCOS-II XMLs, the reconstructed synthetic light curve is also shown. Yellow = natural initial-condition projection; green = flatband charge.')}<span class="chart-meta" id="ditVcpdMeta"></span><span class="grow"></span><button id="e1" title="Export the current-site Vcpd/Qc data, including reconstructed COCOS-II light values when available.">Export</button></header><div class="chart-stage"><div class="chart-legend" id="ditVcpdLegend"></div><svg id="d1" viewBox="0 0 620 285" preserveAspectRatio="none"></svg></div></div>
        <div class="panel chart"><header><b>Dit–Vsb</b>${help('Interface-state density versus surface-barrier magnitude on a logarithmic Y axis. Points are the variation-method values; green is the filtered PCHIP interpolation; yellow marks midgap.')}<span class="chart-meta" id="ditDitMeta"></span><span class="grow"></span><button id="e2" title="Export current-site Vsb, variation Dit and legacy direct-charge Dit.">Export</button></header><div class="chart-stage"><div class="chart-legend" id="ditDitLegend"></div><svg id="d2" viewBox="0 0 620 285" preserveAspectRatio="none"></svg></div></div>
      </section><section class="plots">
        <div class="panel chart"><header><b>Vsb–Qc</b>${help('Surface-barrier magnitude versus corona charge. Standard COCOS uses the XML Vsb correction factor; COCOS-II XMLs use the reconstructed synthetic-light correction. The raw standard Vsb is shown dashed for comparison when COCOS-II is active.')}<span class="chart-meta" id="ditVsbMeta"></span><span class="grow"></span><button id="e3" title="Export current-site raw and analysis Vsb versus Qc.">Export</button></header><div class="chart-stage"><div class="chart-legend" id="ditVsbLegend"></div><svg id="d3" viewBox="0 0 620 285" preserveAspectRatio="none"></svg></div></div>
        <div class="panel chart map-panel"><header><b>Wafer map</b>${help('Map any calculated Dit/COCOS parameter across the measured sites. Each site displays its numeric value; click a site to select it.')}<span class="grow"></span><select id="ditMapMetric"><option value="Qtot">Qtot</option><option value="Dit">Minimum Dit</option><option value="MidgapDit">Midgap Dit</option><option value="EOT">EOT</option><option value="Cox">Cox</option><option value="Qsc">Qsc</option><option value="InitialQc">Initial Qc</option><option value="MaxVsb">Max |Vsb|</option></select><button id="e4" title="Export the selected wafer-map quantity for every site.">Export</button></header><div class="chart-stage map-stage"><svg id="d4" viewBox="0 0 620 315"></svg></div></div>
      </section></div>`;
      host.querySelector('#ditMapMetric').value=mapKey;host.querySelector('#ditSite').onchange=e=>{site=+e.target.value;renderShell()};host.querySelector('#ditPrev').onclick=()=>{if(site>0){site--;renderShell()}};host.querySelector('#ditNext').onclick=()=>{if(site<analysis.sites.length-1){site++;renderShell()}};host.querySelector('#ditDirect').onchange=e=>{showDirect=e.target.checked;drawDit()};host.querySelector('#ditMapMetric').onchange=e=>{mapKey=e.target.value;drawMap()};host.querySelector('#ditRecalc').onclick=rebuild;
      host.querySelector('#e1').onclick=()=>PV.exporter.csv(`Dit_site${site+1}_Vcpd.csv`,['Qc','VDark','Measured VLight','Analysis Vsb','COCOS-II synthetic VLight'],s.rows.map((r,i)=>[r.Qc,r.VDark,r.VLight,s.analysisVsb[i],s.c2?.light?.[i]??'']));
      host.querySelector('#e2').onclick=()=>PV.exporter.csv(`Dit_site${site+1}_Dit.csv`,['Vsb','Variation Dit','Legacy direct Dit'],s.rows.slice(0,-1).map((r,i)=>[s.analysisVsb[i],s.ditRaw[i],s.directRaw[i]]));
      host.querySelector('#e3').onclick=()=>PV.exporter.csv(`Dit_site${site+1}_Vsb.csv`,['Qc','Raw standard |Vsb|','Analysis |Vsb|'],s.rows.map((r,i)=>[r.Qc,r.Vsb,s.analysisVsb[i]]));host.querySelector('#e4').onclick=()=>{const [label,unit]=mapSpec(mapKey);PV.exporter.csv(`Dit_wafer_${mapKey}.csv`,['Site','x','y',label,unit,'Valid'],analysis.sites.map((x,i)=>[i+1,x.coord?.x??'',x.coord?.y??'',metric(x,mapKey),unit,x.valid?'YES':'NO']))};drawAll();
    }
    function drawVcpd(){const s=analysis.sites[site],r=s.rows,svg=host.querySelector('#d1');if(!r.length){svg.innerHTML='';return}const qc=r.map(x=>x.Qc),vd=r.map(x=>x.VDark),vl=r.map(x=>x.VLight),c2=s.c2?.valid?s.c2.light:[],ys=finite([...vd,...vl,...c2,s.VDark]),W=620,H=285,m={l:58,r:12,t:22,b:36},y0=Math.min(...ys),y1=Math.max(...ys),pad=(y1-y0||1)*.05,{X,Y,out:base}=svgAxes(W,H,m,Math.min(...qc),Math.max(...qc),y0-pad,y1+pad),parts=[base,pathXY(qc,vd,X,Y,'var(--red)',2),pathXY(qc,vl,X,Y,'var(--blue)',1.7)];if(c2.length)parts.push(pathXY(qc,c2,X,Y,'var(--green)',2.1,'6,4'));if(Number.isFinite(s.qinit))parts.push(`<line x1="${X(s.qinit)}" x2="${X(s.qinit)}" y1="${m.t}" y2="${H-m.b}" stroke="var(--yellow)" stroke-width="1.3" stroke-dasharray="4,4"/><circle cx="${X(s.qinit)}" cy="${Y(s.VDark)}" r="4" fill="var(--yellow)"><title>Initial projection ${sci(s.qinit,4)}</title></circle>`);if(Number.isFinite(s.qfb))parts.push(`<line x1="${X(s.qfb)}" x2="${X(s.qfb)}" y1="${m.t}" y2="${H-m.b}" stroke="var(--green)" stroke-width="1.3" stroke-dasharray="4,4"><title>Flatband ${sci(s.qfb,4)}</title></line>`);parts.push(`<text x="${W/2}" y="${H-2}" text-anchor="middle" fill="var(--text)" font-size="9">Qc (q/cm²)</text><text x="11" y="${H/2}" transform="rotate(-90 11 ${H/2})" text-anchor="middle" fill="var(--text)" font-size="9">Vcpd (V)</text>`);svg.innerHTML=parts.join('');host.querySelector('#ditVcpdLegend').innerHTML='<span><i style="background:var(--red)"></i>Dark</span><span><i style="background:var(--blue)"></i>Measured light</span>'+(c2.length?'<span><i style="background:var(--green)"></i>COCOS-II synthetic light</span>':'')+'<span class="yellow">│ initial</span><span class="green">│ flatband</span>';host.querySelector('#ditVcpdMeta').textContent=`${analysis.mode} · Qtot ${sci(s.Qtot,2)}`}
    function drawVsb(){const s=analysis.sites[site],r=s.rows,svg=host.querySelector('#d3');if(!r.length){svg.innerHTML='';return}const qc=r.map(x=>x.Qc),raw=r.map(x=>x.Vsb),v=s.analysisVsb,W=620,H=285,m={l:52,r:12,t:22,b:36},ymin=0,ymax=Math.max(...finite([...raw,...v]))*1.05,{X,Y,out:base}=svgAxes(W,H,m,Math.min(...qc),Math.max(...qc),ymin,ymax,{xFmt:x=>x.toExponential(1),yFmt:y=>y.toFixed(2)}),parts=[base,pathXY(qc,v,X,Y,'var(--blue)',2.3)];if(d.useCocosII)parts.push(pathXY(qc,raw,X,Y,'var(--soft)',1.3,'5,4'));if(Number.isFinite(s.qfb))parts.push(`<line x1="${X(s.qfb)}" x2="${X(s.qfb)}" y1="${m.t}" y2="${H-m.b}" stroke="var(--green)" stroke-width="1.3" stroke-dasharray="4,4"/>`);parts.push(`<text x="${W/2}" y="${H-2}" text-anchor="middle" fill="var(--text)" font-size="9">Qc (q/cm²)</text><text x="11" y="${H/2}" transform="rotate(-90 11 ${H/2})" text-anchor="middle" fill="var(--text)" font-size="9">|Vsb| (V)</text>`);svg.innerHTML=parts.join('');host.querySelector('#ditVsbLegend').innerHTML='<span><i style="background:var(--blue)"></i>'+(d.useCocosII?'COCOS-II corrected':'Vsb')+'</span>'+(d.useCocosII?'<span><i style="background:var(--soft)"></i>raw standard</span>':'')+'<span class="green">│ flatband</span>';host.querySelector('#ditVsbMeta').textContent=`max |Vsb| ${fmt(s.MaxVsb,3)} V`}
    function drawDit(){const s=analysis.sites[site],svg=host.querySelector('#d2'),raw=s.ditRaw.map((y,i)=>({x:s.analysisVsb[i],y})).filter(r=>Number.isFinite(r.x)&&Number.isFinite(r.y)&&r.y>0),cur=s.ditCurve||[],dir=showDirect?(s.directCurve||[]):[],xs=finite([...raw.map(x=>x.x),...cur.map(x=>x.x),...dir.map(x=>x.x)]),ys=finite([...raw.map(x=>x.y),...cur.map(x=>x.y),...dir.map(x=>x.y)]).filter(x=>x>0);if(!xs.length||!ys.length){svg.innerHTML='';return}const W=620,H=285,m={l:62,r:12,t:22,b:36},ymin=10**Math.floor(Math.log10(Math.min(...ys))),ymax=10**Math.ceil(Math.log10(Math.max(...ys))),{X,Y,out:base}=svgAxes(W,H,m,Math.min(0,...xs),Math.max(...xs)*1.02,ymin,ymax,{xFmt:x=>x.toFixed(2),yFmt:y=>'1e'+Math.round(Math.log10(y)),logY:true}),parts=[base];raw.forEach(p=>parts.push(`<circle cx="${X(p.x)}" cy="${Y(p.y)}" r="2.1" fill="var(--blue)" opacity=".72"><title>Vsb ${fmt(p.x,4)} V · Dit ${sci(p.y,4)}</title></circle>`));if(cur.length)parts.push(`<polyline points="${cur.filter(p=>p.y>0).map(p=>`${X(p.x)},${Y(p.y)}`).join(' ')}" fill="none" stroke="var(--green)" stroke-width="2.4"/>`);if(dir.length)parts.push(`<polyline points="${dir.filter(p=>p.y>0).map(p=>`${X(p.x)},${Y(p.y)}`).join(' ')}" fill="none" stroke="var(--purple)" stroke-width="1.4" stroke-dasharray="5,4"/>`);if(Number.isFinite(s.midgapV))parts.push(`<line x1="${X(s.midgapV)}" x2="${X(s.midgapV)}" y1="${m.t}" y2="${H-m.b}" stroke="var(--yellow)" stroke-width="1.3" stroke-dasharray="4,4"/>`);parts.push(`<text x="${W/2}" y="${H-2}" text-anchor="middle" fill="var(--text)" font-size="9">|Vsb| (V)</text><text x="11" y="${H/2}" transform="rotate(-90 11 ${H/2})" text-anchor="middle" fill="var(--text)" font-size="9">Dit (cm⁻² eV⁻¹)</text>`);svg.innerHTML=parts.join('');host.querySelector('#ditDitLegend').innerHTML='<span><i style="background:var(--blue)"></i>variation points</span><span><i style="background:var(--green)"></i>PCHIP</span>'+ (showDirect?'<span><i style="background:var(--purple)"></i>legacy direct</span>':'') +'<span class="yellow">│ midgap</span>';host.querySelector('#ditDitMeta').textContent=`${analysis.mode} · min ${sci(s.Dit,2)} · midgap ${sci(s.MidgapDit,2)}`}
    function drawMap(){const svg=host.querySelector('#d4'),[label,unit,log]=mapSpec(mapKey),vals=analysis.sites.map(x=>metric(x,mapKey)),vv=vals.filter(Number.isFinite).map(v=>log&&v>0?Math.log10(v):v),lo=vv.length?Math.min(...vv):0,hi=vv.length?Math.max(...vv):1,W=620,H=315,cx=310,cy=154,R=125,maxRad=Math.max(1,...analysis.sites.map(x=>Math.hypot(x.coord?.x||0,x.coord?.y||0))),scale=R*.72/maxRad;let out=`<rect width="${W}" height="${H}" fill="var(--chart-bg)"/><circle cx="${cx}" cy="${cy}" r="${R}" fill="var(--panel2)" stroke="var(--soft)" stroke-width="2"/><text x="${cx}" y="18" text-anchor="middle" fill="var(--muted)" font-size="10">${esc(label)} [${esc(unit)}]</text>`;analysis.sites.forEach((s,i)=>{const p=s.coord||{x:0,y:0},v=vals[i],z=Number.isFinite(v)?(log&&v>0?Math.log10(v):v):NaN,t=Number.isFinite(z)&&hi>lo?(z-lo)/(hi-lo):.5,col=Number.isFinite(z)?mapColor(t):'#666',x=cx+(p.x||0)*scale,y=cy-(p.y||0)*scale,txt=mapValue(v,mapKey);out+=`<g data-site="${i}" class="map-site"><title>Site ${i+1}: ${txt} ${unit}; x=${fmt(p.x,2)}, y=${fmt(p.y,2)}</title><circle cx="${x}" cy="${y}" r="16" fill="${col}" stroke="${i===site?'var(--text)':s.valid?'var(--border)':'var(--bad)'}" stroke-width="${i===site?3:1.4}"/><text x="${x}" y="${y+3}" text-anchor="middle" fill="#fff" font-size="9" font-weight="700">${i+1}</text><text x="${x}" y="${y+29}" text-anchor="middle" fill="var(--text)" font-size="9" font-weight="600">${txt}</text></g>`});svg.innerHTML=out;svg.querySelectorAll('[data-site]').forEach(g=>g.onclick=()=>{site=+g.dataset.site;renderShell()})}
    function drawAll(){drawVcpd();drawVsb();drawDit();drawMap()}
    document.addEventListener('pv-theme-change',()=>{if(host.isConnected)drawAll()});renderShell();
  }
  PV.modules=PV.modules||{};PV.modules.dit={types:['DITMeasurement'],parse,analyze,render,qsc,flat,cocosII,variation};PV.registry.register(PV.modules.dit);
})(typeof window!=='undefined'?window:globalThis);
